name: Test Install libc++

on:
  workflow_dispatch: 
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        msan: [true, false]

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install libcxx
        uses: ./
        id: install-libcxx
        with:
          libcxx_version: 18.1.3 
          msan: ${{ matrix.msan }}
      - name: Build
        working-directory: test-code
        run: |
          cmake -B build -S . -DCMAKE_CXX_COMPILER=clang++ -DLIBCXX_INCLUDE_PATH=/usr/local/include/build-libcxx -DLIBCXX_LIB_PATH=/usr/local/lib/build-libcxx
          cmake --build build --target all
          