name: Test Install libc++

on:
  workflow_dispatch: 
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        msan: [true, false]

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install libcxx
        uses: ./
        id: install-libcxx
        with:
          libcxx_version: 18.1.3 
          msan: ${{ matrix.msan }}
      - id: msan-flag
        run: |
          MSAN_ENABLED=${{ matrix.msan }}
          if [[ "$MSAN_ENABLED" = "true" ]]; then
            MSAN_FLAG=-DMSAN_FLAGS=ON
          else
            MSAN_FLAG=-DMSAN_FLAGS=OFF
          fi
          echo "msan-flag=$MSAN_FLAG" >> $GITHUB_OUTPUT
      - name: Build
        working-directory: test-code
        run: |
          cmake -B build -S . -DCMAKE_CXX_COMPILER=clang++ -DLIBCXX_INCLUDE_PATH=/usr/local/include/libcxx -DLIBCXX_LIB_PATH=/usr/local/lib/libcxx ${{ steps.msan-flag.outputs.msan-flag }}
          cmake --build build --target all
          